# Generated by Django 5.1.7 on 2025-08-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
    ]
