# Generated by Django 5.1.7 on 2025-08-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='phone_Number',
            new_name='phone_number',
        ),
    ]
