# Generated by Django 5.1.7 on 2025-09-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_friendrequset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequset',
            new_name='FriendRequestModel',
        ),
    ]
