# Generated by Django 5.1.7 on 2025-08-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
